version: '3.8'

services:
  vectordb:
    image: semitechnologies/weaviate
    ports:
      - 8080:8080
    restart: on-failure:0
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
      CLUSTER_GOSSIP_BIND_PORT: '7100'
      CLUSTER_DATA_BIND_PORT: '7101'
    volumes:
      - ./data/weaviate_data:/var/lib/weaviate


volumes:
    weaviate_data:
